### ISSUE TITLE
怎么清除队列里的所有弹幕呢

### ISSUE THREAD

**Issue by jin10086** [yaseng/jquery.barrager.js#1]
$.fn.barrager.removeAll(); 好像只能清除屏幕上有的，而不能清除队列上所有的

我现在的问题是这样的.打开一个图片后，然后加载这个图片的所有弹幕
但是当切换照片的时候,我希望之前一个队列里面的所有弹幕全部中止

**Comment by jin10086** [comment]
原来 setInterval 每次都会生成一个单独的id，只要 把这个id存为全局变量，然后再一开始的时候清除就可以了~~

**Comment by yaseng** [comment]
恩  现在这个id是时间戳,有必要的话可以从外部传入自定义

```
    $.fn.barrager = function(barrage) {
        barrage = $.extend({
            close:true,
            bottom: 0,
            max: 10,
            speed: 6,
            color: '#fff',
            old_ie_color : '#000000'
        }, barrage || {});

        var time = new Date().getTime();
        var barrager_id = 'barrage_' + time;
        var id = '#' + barrager_id;
```

**Comment by zwy-github** [comment]
if(_this.status) {//弹幕开关状态
                        $('#container').barrager(_this.item);
                    }
配合$.fn.barrager.removeAll()使用就可以了
