### ISSUE TITLE
用户是否可以自定义弹幕背景色非字体颜色

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yaseng/jquery.barrager.js#14]
用户是否可以自定义弹幕背景色非字体颜色

**Comment by yaseng** [comment]
修改对应css就行

**Comment by Yakumo-Yukari** [comment]
額 可能我沒表述清楚 我的意思是用戶發表彈幕的時候是否可以選擇彈幕背景的顏色

**Comment by joyjoe** [comment]
弹幕背景色是在CSS里面 .barrage_box 样式里面定义的，你完全可以把这条样式去掉，然后在代码中的div_barrager_box 这个DOM节点变量上添加自己的样式。通过把用户自定义的背景色作为参数中的一个选项传入进去即可。
