### ISSUE TITLE
存在一个bug

### ISSUE THREAD

**Issue by rowthan** [yaseng/jquery.barrager.js#3]
当存在大量弹幕（20条以上） 会明显出现 弹幕的移动速度会整体放慢，如本来设定的setInterval 步长为6 但是当多次点击“弹弹弹”或者采用服务器端读取弹幕信息来输出的时候，弹幕的移动速度明显的下降了。暂时我也找不出原因，猜测是多条弹幕运行 导致浏览器性能下降，弹幕之间发送是采用同步进行的，如果是异步进行可能就没问题了。

**Comment by rowthan** [comment]
可不可以换一种思路 弹幕的滚动不用setinterval来控制？
其他弹幕网站都怎么做的？

**Comment by rowthan** [comment]
我知道一种方式 可以采用animate来实现  但是，亲测有效 弹幕之间不会相互影响速度。但是采用animate 如何实现 弹幕停留等问题呢？

**Comment by yaseng** [comment]
恩  可以考虑考虑

**Comment by zcmzc** [comment]
https://tool.zcmzcm.org/webBarrage
