### ISSUE TITLE
怎么循环播放弹幕？

### ISSUE THREAD

**Issue by ohblue** [yaseng/jquery.barrager.js#6]
数据很少的时候一会儿就飘完了，想让它加载完所有弹幕后再重新加载怎么弄。

**Comment by yaseng** [comment]
多次调用 $('body').barrager({'img':'barrager.png','info':'Hello world!'});    例如定时器

**Comment by zaxfenfeiyu** [comment]
在给出的代码中，只要将清楚计时器改成index=0即可实现循环播放
 function  barrager(){
          if(run_once){
              //如果是首次执行,则设置一个定时器,并且把首次执行置为false
              looper=setInterval(barrager,looper_time);                
              run_once=false;
          }
          //发布一个弹幕
          $('body').barrager(items[index]);
          //索引自增
          index++;
          //所有弹幕发布完毕，清除计时器。
          if(index == total){
              index=0;
          }
        }

**Comment by zouhuigang** [comment]
同问，怎么没设置循环弹幕的？
